---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.8.1

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[test-cookbook::default]
    attributes:
